# Generated by Django 2.2.7 on 2020-01-07 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.IntegerField(choices=[('1', '普通客户'), ('2', '重点客户'), ('3', '其他客户')])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('weChat', models.CharField(blank=True, max_length=20)),
                ('website', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('detail_address', models.CharField(max_length=120)),
                ('is_open_sea', models.BooleanField()),
                ('create_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL)),
                ('customer_industry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.CustomerIndustry')),
                ('head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('weChat', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_key', models.BooleanField()),
                ('job', models.CharField(max_length=20)),
                ('sex', models.IntegerField(choices=[('1', '男'), ('2', '女')])),
                ('next_time', models.TimeField()),
                ('remark', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
            ],
        ),
    ]
